@startuml
' vocabulary
enum SensitivePersonalInformationType {
<b>Summary</b>
Categories of presence or absence
<b>Description</b>
This type is used to indicate if a given field is present or absent or
unknown
.. entries ..
    no : Indicates absence of the field
    noassertion : Describes no assertion. In other words, unknown.
    yes : Indicates presence of the field
}
enum SafetyRiskAssessmentType {
<b>Summary</b>
Categories of safety risk impact of application ie. Serious, high,
medium low
<b>Description</b>
Describes the different safety risk type values that can be used to
describe the safety risk of the AI software
.. entries ..
    high : The second highest level of risk posed by the AI software as given by
Article 20 of EC Regulation No 765/2008.
    low : Low/no risk is contained in the AI software.
    medium : The third highest level of risk as given by Article 20 of EC
Regulation  
No 765/2008.
    serious : The highest level of risk that is contained for a AI software as given
by Article 20 of Regulation 765/2008/EC
}
' classes
together {
class AIPackage {
<b>Summary</b>
MISSING
<b>Description</b>
Metadata information that can be added to a package to describe an AI
application or trained AI model.
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Software:Package
    name : AIPackage
.. properties ..
    autonomyType : PresenceType [0..1]
    dataPreprocessingSteps : xsd:string [0..1]
    domain : xsd:string [0..]
    energyConsumption : xsd:string [0..1]
    hyperparameters : xsd:string [0..]
    informationAboutApplication : xsd:string [0..1]
    informationAboutTraining : xsd:string [0..1]
    limitations : xsd:string [0..]
    metrics : xsd:string [0..]
    metricsDecisionThresholds : xsd:string [0..]
    modelExplainabilityMechanisms : xsd:string [0..1]
    safetyRiskAssessment : SafetyRiskAssessmentType [0..1]
    sensitivePersonalInformation : SensitivePersonalInformationType [0..1]
    standardsCompliance : xsd:string [0..]
    typeOfModel : xsd:string [0..]
}
"PresenceType" <-[dashed,thickness=4]-- "AIPackage::autonomyType"
"SafetyRiskAssessmentType" <-[dashed,thickness=4]-- "AIPackage::safetyRiskAssessment"
"SensitivePersonalInformationType" <-[dashed,thickness=4]-- "AIPackage::sensitivePersonalInformation"
}
"Package" <|-[thickness=4]--- "AIPackage" : Software:Package
@enduml
