@startuml
skinparam packageStyle rectangle
set separator none
' vocabulary
enum BuildTypeVocab {
<b>Summary</b>
MISSING
<b>Description</b>
This is about the vocabulary of build types.
.. entries ..
}
' classes
together {
class Build {
<b>Summary</b>
Class that describes a build instance of software/artifacts.
<b>Description</b>
A build is a representation of the process in which a piece of software
or artifact is built. It encapsulates information related to a build
process and provides an element from which relationships can be created
to describe the build's inputs, outputs, and related entities (e.g.
builders, identities, etc.).

Definitions of "BuildType", "ConfigSource", "Parameters" and
"Environment" follow those defined in [SLSA
provenance](https://slsa.dev/provenance/v0.2).

ExternalIdentifier of type "urlScheme" may be used to identify build
logs. Comment should be "LogReference".
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Core:Element
    name : Build
.. properties ..
    <b>buildId </b>: xsd:string [0..1]
    <b>buildType </b>: anyURI [1..1]
    <b>configSourceDigest </b>: Hash [0..]
    <b>configSourceEntrypoint </b>: xsd:string [0..]
    <b>configSourceUri </b>: anyURI [0..]
    <b>endTime </b>: xsd:DateTime 
    <b>environment </b>: xsd:map&lt;string&gt;string [0..]
    <b>parameters </b>: xsd:map&lt;string&gt;string [0..]
    <b>startTime </b>: xsd:DateTime 
}
"Hash" <-[dashed,thickness=4]-- "Build::configSourceDigest"
}
"Element" <|-[thickness=4]--- "Build" : Core:Element
@enduml
