resolver:
  #url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/14.yaml
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/6.yaml

packages:
- .

nix:
  # enable: true
  packages: [plantuml,graphviz,zlib]