@startuml
enum ExternalIdentifierType {
    cpe22 : TODOdescription
    cpe23 : TODOdescription
    email : TODOdescription
    gitoid : TODOdescription
    other : TODOdescription
    pkgUrl : TODOdescription
    swhid : TODOdescription
    swid : TODOdescription
    urlScheme : TODOdescription
}
note top of ExternalIdentifierType
<b>Summary</b>
TODO
<b>Description</b>
TODO

end note
@enduml
