@startuml
enum ExternalReferenceType {
    altDownloadLocation : TODOdescription
    altWebPage : TODOdescription
    other : TODOdescription
    securityAdvisory : TODOdescription
    securityFix : TODOdescription
    securityOther : TODOdescription
}
note top of ExternalReferenceType
<b>Summary</b>
TODO
<b>Description</b>
TODO

end note
@enduml
