@startuml
!include_once ../Vocabularies/ExternalReferenceType.puml
note right of ExternalReferenceType::altDownloadLocation
    TODOdescription
end note
note right of ExternalReferenceType::altWebPage
    TODOdescription
end note
note right of ExternalReferenceType::other
    TODOdescription
end note
note right of ExternalReferenceType::securityAdvisory
    TODOdescription
end note
note right of ExternalReferenceType::securityFix
    TODOdescription
end note
note right of ExternalReferenceType::securityOther
    TODOdescription
end note
@enduml
