@startuml
enum HashAlgorithm {
    blake2b256
    blake2b384
    blake2b512
    blake3
    md2
    md4
    md5
    md6
    other
    sha1
    sha224
    sha256
    sha384
    sha3_224
    sha3_256
    sha3_384
    sha3_512
    sha512
    spdxPvcSha1
    spdxPvcSha256
}
note top of HashAlgorithm
<b>Summary</b>
TODO
<b>Description</b>
TODO

end note
@enduml
