@startuml
!include_once ../Vocabularies/RelationshipType.puml
note right of RelationshipType::amends
    TODOdescription
end note
note right of RelationshipType::ancestor
    TODOdescription
end note
note right of RelationshipType::buildDependency
    TODOdescription
end note
note right of RelationshipType::buildTool
    TODOdescription
end note
note right of RelationshipType::contains
    TODOdescription
end note
note right of RelationshipType::copy
    TODOdescription
end note
note right of RelationshipType::dataFile
    TODOdescription
end note
note right of RelationshipType::dependencyManifest
    TODOdescription
end note
note right of RelationshipType::dependsOn
    TODOdescription
end note
note right of RelationshipType::descendant
    TODOdescription
end note
note right of RelationshipType::describes
    TODOdescription
end note
note right of RelationshipType::devDependency
    TODOdescription
end note
note right of RelationshipType::devTool
    TODOdescription
end note
note right of RelationshipType::distributionArtifact
    TODOdescription
end note
note right of RelationshipType::documentation
    TODOdescription
end note
note right of RelationshipType::dynamicLink
    TODOdescription
end note
note right of RelationshipType::example
    TODOdescription
end note
note right of RelationshipType::expandedFromArchive
    TODOdescription
end note
note right of RelationshipType::fileAdded
    TODOdescription
end note
note right of RelationshipType::fileDeleted
    TODOdescription
end note
note right of RelationshipType::fileModified
    TODOdescription
end note
note right of RelationshipType::generates
    TODOdescription
end note
note right of RelationshipType::metafile
    TODOdescription
end note
note right of RelationshipType::optionalComponent
    TODOdescription
end note
note right of RelationshipType::optionalDependency
    TODOdescription
end note
note right of RelationshipType::other
    TODOdescription
end note
note right of RelationshipType::packages
    TODOdescription
end note
note right of RelationshipType::patch
    TODOdescription
end note
note right of RelationshipType::prerequisite
    TODOdescription
end note
note right of RelationshipType::providedDependency
    TODOdescription
end note
note right of RelationshipType::requirementFor
    TODOdescription
end note
note right of RelationshipType::runtimeDependency
    TODOdescription
end note
note right of RelationshipType::specificationFor
    TODOdescription
end note
note right of RelationshipType::staticLink
    TODOdescription
end note
note right of RelationshipType::suppliedBy
    TODOdescription
end note
note right of RelationshipType::test
    TODOdescription
end note
note right of RelationshipType::testCase
    TODOdescription
end note
note right of RelationshipType::testDependency
    TODOdescription
end note
note right of RelationshipType::testTool
    TODOdescription
end note
note right of RelationshipType::variant
    TODOdescription
end note
@enduml
