@startuml
class AnonymousPayload {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Payload
    name : AnonymousPayload
.. properties ..
    creationInfo
    imports
    namespaces
}
note top of AnonymousPayload
<b>Summary</b>
TODO
<b>Description</b>
TODO

end note
"Payload" <|-[thickness=4]- "AnonymousPayload"
"CreationInformation" <--- "AnonymousPayload::creationInfo"
"ExternalMap" <--- "AnonymousPayload::imports"
"NamespaceMap" <--- "AnonymousPayload::namespaces"
@enduml
