@startuml
class ExternalReference {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : none
    name : ExternalReference
.. properties ..
    comment : xsd:string
    contentType
    externalReferenceType
    locator : anyURI
}
note right of ExternalReference
<b>Summary</b>
A reference to a resource outside of the scope of SPDX-3.0 content.
<b>Description</b>
An External Reference is a grouping of characteristics unique to the
identity, location and context of a resource outside of the scope of
SPDX-3.0 content.

end note
"MediaType" <-- "ExternalReference::contentType"
"ExternalReferenceType" <-- "ExternalReference::externalReferenceType"
@enduml
