@startuml
!include_once ../Classes/Annotation.puml
!include_once ../Classes/AnonymousPayload.puml
!include_once ../Classes/Artifact.puml
!include_once ../Classes/Bom.puml
!include_once ../Classes/Bundle.puml
!include_once ../Classes/CreationInformation.puml
!include_once ../Classes/Element.puml
!include_once ../Classes/ElementCollection.puml
!include_once ../Classes/Entity.puml
!include_once ../Classes/ExternalIdentifier.puml
!include_once ../Classes/ExternalMap.puml
!include_once ../Classes/ExternalReference.puml
!include_once ../Classes/Hash.puml
!include_once ../Classes/Identity.puml
!include_once ../Classes/IntegrityMethod.puml
!include_once ../Classes/MediaType.puml
!include_once ../Classes/NamespaceMap.puml
!include_once ../Classes/Organization.puml
!include_once ../Classes/Payload.puml
!include_once ../Classes/Person.puml
!include_once ../Classes/ProfileIdentifier.puml
!include_once ../Classes/Relationship.puml
!include_once ../Classes/SemVer.puml
!include_once ../Classes/SpdxDocument.puml
!include_once ../Classes/Tool.puml
@enduml
