@startuml
!include_once ../Classes/Annotation.commented.puml
!include_once ../Classes/AnonymousPayload.commented.puml
!include_once ../Classes/Artifact.commented.puml
!include_once ../Classes/Bom.commented.puml
!include_once ../Classes/Bundle.commented.puml
!include_once ../Classes/CreationInformation.commented.puml
!include_once ../Classes/Element.commented.puml
!include_once ../Classes/ElementCollection.commented.puml
!include_once ../Classes/Entity.commented.puml
!include_once ../Classes/ExternalIdentifier.commented.puml
!include_once ../Classes/ExternalMap.commented.puml
!include_once ../Classes/ExternalReference.commented.puml
!include_once ../Classes/Hash.commented.puml
!include_once ../Classes/Identity.commented.puml
!include_once ../Classes/IntegrityMethod.commented.puml
!include_once ../Classes/MediaType.commented.puml
!include_once ../Classes/NamespaceMap.commented.puml
!include_once ../Classes/Organization.commented.puml
!include_once ../Classes/Payload.commented.puml
!include_once ../Classes/Person.commented.puml
!include_once ../Classes/ProfileIdentifier.commented.puml
!include_once ../Classes/Relationship.commented.puml
!include_once ../Classes/SemVer.commented.puml
!include_once ../Classes/SpdxDocument.commented.puml
!include_once ../Classes/Tool.commented.puml
@enduml
