@startuml
abstract IntegrityMethod {
.. metadata ..
    Instantiability : Abstract
    name : IntegrityMethod
.. properties ..
    comment : xsd:string
}
note top of IntegrityMethod
<b>Summary</b>
TODO
<b>Description</b>
TODO

end note
@enduml
