@startuml
class SpdxDocument {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Bundle
    name : SpdxDocument
.. properties ..
    name : xsd:string
}
note top of SpdxDocument
<b>Summary</b>
TODO
<b>Description</b>
TODO

end note
"Bundle" <|-- "SpdxDocument"
@enduml
