@startuml
class Tool {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Entity
    name : Tool
.. properties ..
}
note top of Tool
<b>Summary</b>
An element of hardware and/or software utilized to carry out a
particular function.
<b>Description</b>
A Tool is an element of hardware and/or software utilized to carry out a
particular function.

end note
"Entity" <|-[thickness=4]- "Tool"
@enduml
