@startuml
class AIPackage {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Software:Package
    name : AIPackage
.. properties ..
    autonomyType : PresenceType [0..1]
    contentIdentifier : anyURI [0..1]
    dataPreprocessingSteps : xsd:string [0..1]
    domain : xsd:string [0..]
    downloadLocation : anyURI [0..1]
    energyConsumption : xsd:string [0..1]
    homePage : anyURI [0..1]
    hyperparameters : xsd:string [0..]
    informationAboutApplication : xsd:string [0..1]
    informationAboutTraining : xsd:string [0..1]
    limitations : xsd:string [0..]
    metrics : xsd:string [0..]
    metricsDecisionThresholds : xsd:string [0..]
    modelExplainabilityMechanisms : xsd:string [0..1]
    packagePurpose : SoftwarePurpose [0..]
    packageUrl : anyURI [0..1]
    safetyRiskAssessment : SafetyRiskAssessmentType [0..1]
    sensitivePersonalInformation : PresenceType [0..1]
    standardsCompliance : xsd:string [0..]
    typeOfModel : xsd:string [0..]
}
note top of AIPackage
<b>Summary</b>
MISSING
<b>Description</b>
Metadata information that can be added to a package to describe an AI
application or trained AI model.
end note
"Software:Package" <|-[thickness=4]- "AIPackage"
"PresenceType" <-[dotted]-- "AIPackage::autonomyType"
"SoftwarePurpose" <-[dotted]-- "AIPackage::packagePurpose"
"SafetyRiskAssessmentType" <-[dotted]-- "AIPackage::safetyRiskAssessment"
"PresenceType" <-[dotted]-- "AIPackage::sensitivePersonalInformation"
@enduml
