@startuml
set separator ::
enum AnnotationType {
    other : Used to store extra information about an Element which is not part of a
Review (e.g. extra information provided during the creation of the
Element).
    review : Used when someone reviews the Element.
}
note top of AnnotationType
<b>Summary</b>
Specifies the type of an annotation.
<b>Description</b>
AnnotationType specifies the type of an annotation.
end note
@enduml
