@startuml
abstract Artifact {
.. metadata ..
    Instantiability : Abstract
    SubclassOf : Element
    name : Artifact
.. properties ..
    originatedBy : Identity [0..]
}
note top of Artifact
<b>Summary</b>
A distinct article or unit within the digital domain.
<b>Description</b>
An artifact is a distinct article or unit within the digital domain,
such as an electronic file, a software package, a device or an element
of data.
end note
"Element" <|-[thickness=4]- "Artifact"
"Identity" <-[dotted]-- "Artifact::originatedBy"
@enduml
