@startuml
set separator ::
class Build {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Core:Element
    name : Build
.. properties ..
    buildId : xsd:string [0..1]
    buildType : anyURI [1..1]
    configSourceDigest : Hash [0..]
    configSourceEntrypoint : xsd:string [0..]
    configSourceUri : anyURI [0..]
    endTime : xsd:DateTime 
    environment : xsd:map&lt;string&gt;string [0..]
    parameters : xsd:map&lt;string&gt;string [0..]
    startTime : xsd:DateTime 
}
note top of Build
<b>Summary</b>
Class that describes a build instance of software/artifacts.
<b>Description</b>
A build is a representation of the process in which a piece of software
or artifact is built. It encapsulates information related to a build
process and provides an element from which relationships can be created
to describe the build's inputs, outputs, and related entities (e.g.
builders, identities, etc.).

Definitions of "BuildType", "ConfigSource", "Parameters" and
"Environment" follow those defined in [SLSA
provenance](https://slsa.dev/provenance/v0.2).

ExternalIdentifier of type "urlScheme" may be used to identify build
logs. Comment should be "LogReference".
end note
"Core:Element" <|-[thickness=4]- "Build"
"Core::Element" -[thickness=4]-- "Core:Element"
"Hash" <-[dotted]-- "Build::configSourceDigest"
@enduml
