@startuml
class CopyrightText {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : CopyrightTextField
    name : CopyrightText
.. properties ..
    text : xsd:string [1..1]
}
note top of CopyrightText
<b>Summary</b>
Concrete class representing copyright text that has actually been found.
<b>Description</b>
A CopyrightText is the primary value that is used by a copyrightText
field that indicates copyright text being found, i.e. with a value other
than NONE or NOASSERTION.
end note
"CopyrightTextField" <|-[thickness=4]- "CopyrightText"
@enduml
