@startuml
' vocabulary
!include_once AnnotationType.puml
!include_once ExternalIdentifierType.puml
!include_once ExternalReferenceType.puml
!include_once HashAlgorithm.puml
!include_once RelationshipCompleteness.puml
!include_once RelationshipType.puml
' classes
!include_once Annotation.puml
!include_once AnonymousPayload.puml
!include_once Artifact.puml
!include_once Bom.puml
!include_once Bundle.puml
!include_once CreationInformation.puml
!include_once Element.puml
!include_once ElementCollection.puml
!include_once Entity.puml
!include_once ExternalIdentifier.puml
!include_once ExternalMap.puml
!include_once ExternalReference.puml
!include_once Hash.puml
!include_once Identity.puml
!include_once IntegrityMethod.puml
!include_once MediaType.puml
!include_once NamespaceMap.puml
!include_once Organization.puml
!include_once Payload.puml
!include_once Person.puml
!include_once ProfileIdentifier.puml
!include_once Relationship.puml
!include_once SemVer.puml
!include_once SpdxDocument.puml
!include_once Tool.puml
@enduml
