@startuml
class CreationInformation {
.. metadata ..
    Instantiability : Concrete
    name : CreationInformation
.. properties ..
    comment : xsd:string [0..1]
    created : xsd:dateTime 
    createdBy : Entity [1..]
    dataLicense : xsd:string 
    profile : ProfileIdentifier [1..]
    specVersion : SemVer 
}
note top of CreationInformation
<b>Summary</b>
Provides information about the creation of the Element.
<b>Description</b>
The CreationInformation provides information about who created the
Element, and when and how it was created.
end note
"Entity" <-[dotted]-- "CreationInformation::createdBy"
"ProfileIdentifier" <-[dotted]-- "CreationInformation::profile"
"SemVer" <-[dotted]-- "CreationInformation::specVersion"
@enduml
