@startuml
enum DependencyScope {
    build : TODOdescription
    dev : TODOdescription
    noAssertion : TODOdescription
    other : TODOdescription
    runtime : TODOdescription
    test : TODOdescription
}
note top of DependencyScope
<b>Summary</b>
TODO
<b>Description</b>
TODO
end note
@enduml
