@startuml
set separator ::
class Entity {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Element
    name : Entity
.. properties ..
}
note top of Entity
<b>Summary</b>
TODO
<b>Description</b>
TODO
end note
"Element" <|-[thickness=4]- "Entity"
@enduml
