@startuml
set separator ::
class ExternalIdentifier {
.. metadata ..
    Instantiability : Concrete
    name : ExternalIdentifier
.. properties ..
    comment : xsd:string [0..1]
    externalIdentifierType : ExternalIdentifierType [1..1]
    identifier : xsd:string [1..1]
}
note top of ExternalIdentifier
<b>Summary</b>
A reference to a resource outside the scope of SPDX-3.0 content that
uniquely identifies an Element.
<b>Description</b>
An ExternalIdentifier is a reference to a resource outside the scope of
SPDX-3.0 content that uniquely identifies an Element.
end note
"ExternalIdentifierType" <-[dotted]-- "ExternalIdentifier::externalIdentifierType"
@enduml
