@startuml
set separator ::
class ExternalReference {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : none
    name : ExternalReference
.. properties ..
    comment : xsd:string [..1]
    contentType : MediaType [..1]
    externalReferenceType : ExternalReferenceType [..1]
    locator : anyURI 
}
note top of ExternalReference
<b>Summary</b>
A reference to a resource outside the scope of SPDX-3.0 content.
<b>Description</b>
An External Reference points to a resource outside the scope of the
SPDX-3.0 content that provides additional characteristics of an Element.
end note
"MediaType" <-[dotted]-- "ExternalReference::contentType"
"ExternalReferenceType" <-[dotted]-- "ExternalReference::externalReferenceType"
@enduml
