@startuml
set separator ::
class File {
.. metadata ..
    SubclassOf : Core:Artifact
    name : File
.. properties ..
    contentIdentifier : anyURI [0..1]
    contentType : MediaType [0..1]
    filePurpose : SoftwarePurpose [0..]
}
note top of File
<b>Summary</b>
MISSING
<b>Description</b>
TODO This is about the File class.
end note
"Core:Artifact" <|-[thickness=4]- "File"
"Core::Artifact" -[thickness=4]-- "Core:Artifact"
"MediaType" <-[dotted]-- "File::contentType"
"SoftwarePurpose" <-[dotted]-- "File::filePurpose"
@enduml
