@startuml
enum HashAlgorithm {
    blake2b256 : TODOdescription
    blake2b384 : TODOdescription
    blake2b512 : TODOdescription
    blake3 : TODOdescription
    md2 : TODOdescription
    md4 : TODOdescription
    md5 : TODOdescription
    md6 : TODOdescription
    other : TODOdescription
    sha1 : TODOdescription
    sha224 : TODOdescription
    sha256 : TODOdescription
    sha384 : TODOdescription
    sha3_224 : TODOdescription
    sha3_256 : TODOdescription
    sha3_384 : TODOdescription
    sha3_512 : TODOdescription
    sha512 : TODOdescription
    spdxPvcSha1 : TODOdescription
    spdxPvcSha256 : TODOdescription
}
note top of HashAlgorithm
<b>Summary</b>
TODO
<b>Description</b>
TODO
end note
@enduml
