@startuml
set separator ::
class Identity {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Entity
    name : Identity
.. properties ..
}
note top of Identity
<b>Summary</b>
An individual or organization.
<b>Description</b>
An Identity is a grouping of identifying characteristics unique to an
individual or organization.
end note
"Entity" <|-[thickness=4]- "Identity"
@enduml
