@startuml
set separator ::
class NoneLicense {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : LicenseField
    name : NoneLicense
.. properties ..
}
note top of NoneLicense
<b>Summary</b>
Concrete class representing an assertion that no license information is
present, as applicable.
<b>Description</b>
**TBD** whether the meaning of NoneLicense in the context of the
concludedLicense and declaredLicense properties should be here rather
than in those property definitions

A NoneLicense is the primary value that is used by a concludedLicense or
declaredLicense field that indicates the absence of license information
from the corresponding software Package, File or Snippet.

The specific meaning of NoneLicense in the context of a concludedLicense
or declaredLicense field is more fully set forth in the Property
definitions for those fields.
end note
"LicenseField" <|-[thickness=4]- "NoneLicense"
@enduml
