@startuml
set separator ::
class OrLaterOperator {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : LicenseExpression
    name : OrLaterOperator
.. properties ..
    license : License [1..1]
}
note top of OrLaterOperator
<b>Summary</b>
Portion of a LicenseExpression representing this version, or any later
version, of the indicated License.
<b>Description</b>
An OrLaterOperator indicates that this portion of the LicenseExpression
represents either (1) the specified version of the corresponding
License, or (2) any later version of that License. It is represented in
the SPDX License Expression Syntax by the `+` operator.

It is context-dependent, and unspecified by SPDX, as to what constitutes
a "later version" of any particular License. Some Licenses may not be
versioned, or may not have clearly-defined ordering for versions. The
consumer of SPDX data will need to determine for themselves what meaning
to attribute to a "later version" operator for a particular License.
end note
"LicenseExpression" <|-[thickness=4]- "OrLaterOperator"
"License" <-[dotted]-- "OrLaterOperator::license"
@enduml
