@startuml
class Package {
.. metadata ..
    SubclassOf : Core:Artifact
    name : Package
.. properties ..
    contentIdentifier : anyURI [0..1]
    downloadLocation : anyURI [0..1]
    homePage : anyURI [0..1]
    packagePurpose : SoftwarePurpose [0..]
    packageUrl : anyURI [0..1]
}
note top of Package
<b>Summary</b>
MISSING
<b>Description</b>
TODO
end note
"Core:Artifact" <|-[thickness=4]- "Package"
"SoftwarePurpose" <--- "Package::packagePurpose"
@enduml
