@startuml
abstract Payload {
.. metadata ..
    Instantiability : Abstract
    SubclassOf : none
    name : Payload
.. properties ..
    creationInfo : CreationInformation [0..1]
    imports : ExternalMap 
    namespaces : NamespaceMap 
}
note top of Payload
<b>Summary</b>
TODO
<b>Description</b>
TODO
end note
"CreationInformation" <--- "Payload::creationInfo"
"ExternalMap" <--- "Payload::imports"
"NamespaceMap" <--- "Payload::namespaces"
@enduml
