@startuml
class ProfileIdentifier {
.. metadata ..
    SubclassOf : xsd:string
    name : ProfileIdentifier
.. properties ..
}
note top of ProfileIdentifier
<b>Summary</b>
TODO
<b>Description</b>
TODO
end note
@enduml
