@startuml
class Relationship {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Element
    name : Relationship
.. properties ..
    completeness : RelationshipCompleteness [0..1]
    from : Element [1..1]
    relationshipType : RelationshipType [..1]
    to : Element [1..]
}
note top of Relationship
<b>Summary</b>
Describes a relationship between one or more elements.
<b>Description</b>
A Relationship is a grouping of characteristics unique to an assertion
that one Element is related to one or more other Elements in some way.
end note
"Element" <|-[thickness=4]- "Relationship"
"RelationshipCompleteness" <-[dotted]-- "Relationship::completeness"
"Element" <-[dotted]-- "Relationship::from"
"RelationshipType" <-[dotted]-- "Relationship::relationshipType"
"Element" <-[dotted]-- "Relationship::to"
@enduml
