@startuml
set separator ::
enum RelationshipCompleteness {
    complete : The relationship is known to be exhaustive.
    incomplete : The relationship is known not to be exhaustive.
    unknown : There can be made no assertion about the completeness of the
relationship.
}
note top of RelationshipCompleteness
<b>Summary</b>
Indicates whether a relationship is complete or known to be incomplete
or if there is made no assertion either way.
<b>Description</b>
RelationshipCompleteness indicates whether a relationship is complete or
known to be incomplete or if there is made no assertion either way.
end note
@enduml
