@startuml
set separator ::
enum SafetyRiskAssessmentType {
    high : The second highest level of risk posed by the AI software as given by
Article 20 of EC Regulation No 765/2008.
    low : Low/no risk is contained in the AI software.
    medium : The third highest level of risk as given by Article 20 of EC
Regulation  
No 765/2008.
    serious : The highest level of risk that is contained for a AI software as given
by Article 20 of Regulation 765/2008/EC
}
note top of SafetyRiskAssessmentType
<b>Summary</b>
Categories of safety risk impact of application ie. Serious, high,
medium low
<b>Description</b>
Describes the different safety risk type values that can be used to
describe the safety risk of the AI software
end note
@enduml
