@startuml
class SemVer {
.. metadata ..
    SubclassOf : xsd:string
    name : SemVer
.. properties ..
}
note top of SemVer
<b>Summary</b>
A String constrained to the SemVer 2.0.0 specification.
<b>Description</b>
The semantic version is a String constrained to the SemVer 2.0.0
specification.
end note
@enduml
