@startuml
' vocabulary
!include_once DependencyLinkType.Vocabulary.puml
!include_once DependencyRequirement.Vocabulary.puml
!include_once DependencyScope.Vocabulary.puml
!include_once SoftwarePurpose.Vocabulary.puml
' classes
!include_once File.Class.puml
!include_once Package.Class.puml
!include_once Sbom.Class.puml
!include_once Snippet.Class.puml
!include_once SoftwareDependencyRelationship.Class.puml
@enduml
