@startuml
class SpdxDocument {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : Bundle
    name : SpdxDocument
.. properties ..
    name : xsd:string [1..1]
}
note top of SpdxDocument
<b>Summary</b>
Assembles a collection of Elements under a common string, the name of
the document.
<b>Description</b>
An SpdxDocument assembles a collection of Elements under a common
string, the name of the document. Commonly used when representing a unit
of transfer of SPDX Elements.
end note
"Bundle" <|-[thickness=4]- "SpdxDocument"
@enduml
