@startuml
package AI {
!include_once AI.puml
}
note top of AI
<b>Summary</b>
Additional metadata based on software profile, that is useful for ai
applications and models.
<b>Description</b>
The AI profile namespace defines concepts related to AI application and
model artifacts.
end note
package Core {
!include_once Core.puml
}
note top of Core
<b>Summary</b>
The basis for all SPDX profiles.
<b>Description</b>
The Core namespace defines foundational concepts serving as the basis
for all SPDX-3.0 profiles.
end note
package Software {
!include_once Software.puml
}
note top of Software
<b>Summary</b>
Everything having to do with software.
<b>Description</b>
The Software namespace defines concepts related to software artifacts.
end note
@enduml
