@startuml
class TODO-missing-name {
.. metadata ..
    SubclassOf : Core:Artifact
.. properties ..
    byteRange : positiveIntegerRange [0..1]
    contentIdentifier : anyURI [0..1]
    lineRange : positiveIntegerRange [0..1]
    snippetPurpose : SoftwarePurpose [0..]
}
note top of TODO-missing-name
<b>Summary</b>
MISSING
<b>Description</b>
TODO
end note
"Core:Artifact" <|-[thickness=4]- "TODO-missing-name"
"positiveIntegerRange" <-[dotted]-- "TODO-missing-name::byteRange"
"positiveIntegerRange" <-[dotted]-- "TODO-missing-name::lineRange"
"SoftwarePurpose" <-[dotted]-- "TODO-missing-name::snippetPurpose"
@enduml
