@startuml
class WithExceptionOperator {
.. metadata ..
    Instantiability : Concrete
    SubclassOf : LicenseExpression
    name : WithExceptionOperator
.. properties ..
}
note top of WithExceptionOperator
<b>Summary</b>
**TBD** Not to be completed until the Change Proposal at
https://github.com/spdx/change-proposal/issues/4 is decided upon. Should
be treated as unconfirmed since this class and its name or meaning is
subject to change.
<b>Description</b>
MISSING
end note
"LicenseExpression" <|-[thickness=4]- "WithExceptionOperator"
@enduml
